# -*- coding: utf-8 -*-
#
# IDAES documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.

import importlib
import os
import sys
import sphinx_book_theme as theme

# For importing from idaes.<modules..>
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("."))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "sphinx.ext.autosectionlabel",
    "sphinxarg.ext",
    "sphinx.ext.doctest",
    "sphinx_copybutton",
    "nbsphinx",
    # MystMD extensions
    "myst_parser",
    "autodoc2",
]

# Myst autodoc2 (experimental)
# note: putting tests in 'exclude_dirs' avoids a WARNING about some duplicated
#       objects in the hda_*.py files.
autodoc2_packages = [{"path": "../src/idaes_fi", "exclude_dirs": ["tests"]}]
autodoc2_output_dir = "apidoc/"
autodoc2_render_plugin = "myst"
# These should be listed from most to least specific,
# since the first match is used
autodoc2_docstring_parser_regexes = [
    # render docstrings in matching files as Markdown
    ("../src/idaes_fi/.*", "myst"),
]
autodoc2_no_index = False
autodoc2_index_template = None  # don't write index.rst
# Put type hints in the description, not signature
autodoc_typehints = "description"

# Nitpicky mode reports unresolved links for generated type annotations from
# external libraries and a few legacy references in source docstrings. Keep
# internal API references checked, but do not require external inventories.
nitpick_ignore = [
    ("py:class", "idaes_fi.structfs.runner.Actions"),
    ("py:class", "structfs.fsrunner.Context"),
]
nitpick_ignore_regex = [
    (r"py:.*", r"abc\..*"),
    (r"py:.*", r"collections\.abc\..*"),
    (r"py:.*", r"enum\..*"),
    (r"py:.*", r"idaes\..*"),
    (r"py:.*", r"logging\..*"),
    (r"py:.*", r"pathlib\..*"),
    (r"py:.*", r"pydantic\..*"),
    (r"py:.*", r"types\..*"),
]

# Avoid duplicating heading labels across parallelly constructed documentation
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The encoding of source files.
#
# source_encoding = 'utf-8-sig'

# The main toctree document.
main_doc = "index"

# General information about the project.
project = "Flowsheet Inspector"
copyright = "2026, PrOMMiS"
author = "PrOMMiS project contributors"


# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = importlib.metadata.version("idaes_fi")
# The full version, including alpha/beta/rc tags.
release = importlib.metadata.version("idaes_fi")

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = [
    "apidoc/*tests*",
    "build",
    "build/**",
    "_build",
    "_build/**",
]

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Global constants for supported Python versions
IDAES_PV_MIN, IDAES_PV_MAX, IDAES_PV_DEFAULT = "3.9", "3.13", "3.12"

# This block of text will be virtually present at the end of every file.
# Used here to define substitutions for re-used URLs, e.g. just add "|examples-site|" to
# any page and it will be replaced with the hyperlink and text shown below.

rst_epilog = f"""
.. |python-min| replace:: {IDAES_PV_MIN}
.. |python-max| replace:: {IDAES_PV_MAX}
.. |github-issues| replace:: `Github issues page`_
.. _Github issues page: https://github.com/IDAES/idaes-pse/issues
"""


class RobustReplacements(dict):
    """These replacements are needed because the Sphinx replacements are
    not expanded within code blocks.
    """

    def __call__(self, app, docname, source):
        text = source[0]
        for to_replace, replace_with in self.items():
            text = text.replace(to_replace, replace_with)
        source[0] = text


_python_versions_replacements = RobustReplacements(
    {
        "|python-min|": IDAES_PV_MIN,
        "|python-max|": IDAES_PV_MAX,
        "|python-default|": IDAES_PV_DEFAULT,
    }
)

# Intersphinx configuration (added 02/22/2024 -Dan G.)
# - To use in doc files, prefix cross-references with ':external:'
# - To explicitly choose an external project prefix with ':external+NAME:',
#   where NAME matches one of the dictionary keys below.
# intersphinx_mapping = {
#     # Python standard library.
#     "python": ("https://docs.python.org/3", None),
#     # add links to idaes-ui
#     "ui": ("https://idaes-ui.readthedocs.io/en/latest/", None),
#     # add links to Pyomo
#     "pyomo": ("https://pyomo.readthedocs.io/en/stable/", None),
# }

# nbsphinx notebook execution
# other options are "never" and "always"
nbsphinx_execute = "auto"


# -- Options for HTML output ----------------------------------------------

html_theme = "sphinx_book_theme"
html_theme_options = {
    "logo": {
        "image_light": "images/logo-text-black.png",
        "image_dark": "images/logo-text-white.png",
    },
    "repository_provider": "github",
    "repository_url": "https://github.com/prommis/flowsheet-inspector-lib",
    "use_repository_button": True,
    "path_to_docs": "docs",
    "extra_footer": """<p>This work was sponsored by the Department of Energy,
    Hydrocarbon and Geothermal Energy Office</p>""",
}
html_theme_path = [theme.get_html_theme_path()]
html_title = "FI v{}".format(release)
html_logo = "images/logo-symbol-fi_100x100.png"
html_favicon = "images/logo-symbol-fi.ico"
html_static_path = ["static", "images"]
html_css_files = ["css/custom.css", "css/badge_only.css"]
html_extra_path = ["static/extra/"]
htmlhelp_basename = "FlowsheetInspectorDoc"

# Sphinx-copybutton options
# XXX: This does not add the button to blockquotes, for some reason
# copybutton_selector = "div.highlight pre,blockquote"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    "preamble": r"\usepackage{enumitem}\setlistdepth{99}",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (main_doc, "IDAES.tex", "IDAES Documentation", "IDAES team", "manual")
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = []

# If true, show URL addresses after external links.
#
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        main_doc,
        "Flowsheet Inspector Library",
        "Flowsheet Inspector Library Documentation",
        author,
        "Flowsheet Inspector Library",
        "Library for PrOMMiS Flowsheet Inspector",
        "Miscellaneous",
    )
]


def setup(app):
    app.connect("source-read", _python_versions_replacements)
